### ISSUE TITLE
支付demo中 少东西

### ISSUE THREAD

**Issue by chrisLeeCreate** [Cuieney/RxPay#1]
Error:/Users/cuieneydemacbook/Desktop/Demo/RxPay-master2/local.properties (No such file or directory)

没有local.properties

**Comment by chrisLeeCreate** [comment]
找到问题了， 是gradle中，你配置bintray的配置信息， 在我电脑上路径不一样，我注释一下 就ok了。哈哈

**Comment by Cuieney** [comment]
@chrisLeeCreate 这匆忙提交 忘记注释了 大兄弟给力
