### ISSUE TITLE
v2.1.6版本调用微信支付，无法调起支付

### ISSUE THREAD

**Issue by xinnuo** [Cuieney/RxPay#6]
{"appId":"wx6353102e13eeeceb","nonceStr":"1524905242893","packageValue":"Sign=WXPay","partnerId":"1499449192","prepayId":"wx28164722759946489ab5d4850655442038","sign":"FA0F67C6EC4F8157F7C9BBCF3D2303EC","timeStamp":"1524905242"}

微信调用后台返回的上面的json，版本2.1.6调用没反应，版本2.1.2的正常，这是什么原因？？？

**Comment by Cuieney** [comment]
最好用最新版本吧2.1.7，兼容性强一点 之前的版本都是在fix bug  可能会出现问题
